spring.application.name=GameArenaAPI

# Example: jdbc:postgresql://<host>:5432/<database_name>
spring.datasource.url=${DB_URL}
# Example: postgres
spring.datasource.username=${DB_USERNAME}
# Example: mysecretpassword
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
server.port=${PORT:8080}
