spring.application.name=GameArenaAPI

# Example: jdbc:postgresql://<host>:5432/<database_name>
# spring.datasource.url=${DB_URL}
spring.datasource.url=jdbc:postgresql://localhost:5432/gamearenadb

# Example: postgres
# spring.datasource.username=${DB_USERNAME}
spring.datasource.username=gamer

# Example: mysecretpassword
#spring.datasource.password=${DB_PASSWORD}
spring.datasource.password=mysecretpassword

spring.datasource.driver-class-name=org.postgresql.Driver

#server.port=${PORT:8080}
server.port=8080

#spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.show-sql=true
