spring.application.name=GameArenaAPI

spring.config.import=optional:file:.env[.properties]

jwt.secret=${JWT_SECRET}
# jwt.secret=zOPWepPHUfaRCCR9xHgSemJ9eiO4E6mFo7/u7/MOaug=
jwt.expiration.default=3600
jwt.expiration.rememberMe=2592000

spring.datasource.url=${DB_URL}
# spring.datasource.url=jdbc:postgresql://localhost:5432/gamearenadb

# Example: postgres
spring.datasource.username=${DB_USERNAME}
# spring.datasource.username=gamer

# Example: mysecretpassword
spring.datasource.password=${DB_PASSWORD}
# spring.datasource.password=mysecretpassword

spring.datasource.driver-class-name=org.postgresql.Driver

#server.port=${PORT:8080}
server.port=5762

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
